version: 2

sources:
  - name: medical
    description: Medical radiology audit data loaded from CSVs
    database: warehouse
    schema: medical

    tables:
      - name: radiology_audits
        description: Radiology audit records with scores and metadata
        columns:
          - name: sr_no
            description: Serial number
            tests:
              - not_null
              - unique
          - name: case_id
            description: Case identifier
          - name: age
            description: Patient age
          - name: gender
            description: Patient gender
          - name: modality
            description: Scan modality (e.g., CT, MRI, X-ray)
          - name: study_description
            description: Description of the study
          - name: sub_specialty
            description: Sub-specialty area
          - name: scan_type
            description: Type of scan
          - name: body_part
            description: Body part scanned
          - name: body_part_category
            description: Category of body part
          - name: scan_date_and_time
            description: Timestamp of scan
          - name: report_date_and_time
            description: Timestamp of report
          - name: case_upload_date_and_time
            description: Timestamp of case upload
          - name: original_radiologist_name
            description: Name of original radiologist
          - name: institute_name
            description: Name of institute
          - name: final_output
            description: Final CAT output
          - name: quality_score
            description: Quality score
          - name: safety_score
            description: Safety score
          - name: star_score
            description: Star score

      - name: question_weightage
        description: Weightage for audit questions
        columns:
          - name: question_no
            description: Question number identifier
          - name: category
            description: Question category
          - name: responsibility
            description: Responsibility (RAD vs ORG)
          - name: percentage_weightage
            description: Weightage percentage

      - name: scoring_rubric
        description: Rubric for scoring questions
        columns:
          - name: question_no
            description: Question number
          - name: actual_question
            description: Text of the question
          - name: score_0
            description: Value for score 0
          - name: score_5
            description: Value for score 5
