
{{ config(materialized='view') }}

WITH source AS (
    SELECT * FROM {{ source('medical', 'radiology_audits') }}
)

SELECT
    id,
    sr_no,
    case_id,
    age,
    gender,
    modality,
    study_description,
    sub_specialty,
    scan_type,
    body_part,
    body_part_category,
    scan_date_and_time,
    report_date_and_time,
    case_upload_date_and_time,
    case_assigned_dated_and_time,
    review_completed_date_and_time_1,
    original_radiologist_name,
    review_radiologist_name_1,
    time_of_the_day_report_generated,
    unit_identifier,
    institute_name,
    assign_tat,
    review_tat,
    q1,
    q2,
    q3,
    q4,
    q5,
    q6,
    q7,
    q8,
    q9,
    q10,
    q11,
    q12_q,
    q12_s,
    q13,
    q14,
    q15,
    q16,
    q17,
    unable_to_audit,
    second_review,
    required_reaudit,
    comments,
    final_output,
    safety_score,
    quality_score,
    productivity_score,
    efficiency_score,
    star_score,
    star
FROM source
